version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
    - mongo
    networks:
      - mynetwork

  redis:
    depends_on:
      - mongo
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - mynetwork

  backend:
    build:
      context: ./Small-MongoDB-Redis-Project
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - mongo
      - redis
    ports:
      - '8080:8080'
    networks:
      - mynetwork

  frontend:
    build:
      context: ./Kubernetes-Project-Frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - mynetwork
volumes:
  data: {}

networks:
  mynetwork: